<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "tw_events"
 *
 * Auto generated by Extension Builder 2019-01-06
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title'            => 'tollwerk Event Calendar',
    'description'      => 'Event management for meetups and conferences',
    'category'         => 'plugin',
    'author'           => 'Joschi Kuphal',
    'author_email'     => 'joschi@tollwerk.de',
    'state'            => 'beta',
    'uploadfolder'     => 1,
    'createDirs'       => '',
    'clearCacheOnLoad' => 0,
    'version'          => '0.1.0',
    'constraints'      => [
        'depends'   => [
            'typo3'              => '9.5.0-9.5.99',
            'static_info_tables' => '6.7.0-',
            'tw_base'            => '2.1.0-',
            'vhs'                => '5.1.0-',
        ],
        'conflicts' => [],
        'suggests'  => [],
    ],
];
